### PR TITLE
Update camera awesome dependency to fix conflicting classes

### PR DESCRIPTION
**Pull request by demolaf**
## Description
Conflicting class from the flutter SDK and Camera Awesome package i.e. CarouselController.

Fixes #(issue number)

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please describe):

## Checklist

Please review the following list before submitting your pull request:

- [ ] I have read the [contributing guidelines](CONTRIBUTING.md)
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots (if applicable)

If applicable, add screenshots to help explain your changes.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

## Linked Issues

If this pull request is related to one or more issues, please list them here:

- Closes # (issue)
- Related to # (issue)

---

Thank you for your contribution! Please review the checklist and ensure that all items are completed before submitting your pull request.

### CODE REVIEW

**Comment by HenrySarukh** [comment]
Can you please merge this PR, we really need it?

**Comment by GhagSagar23** [comment]
Hi @HenrySarukh, can you please update the following details?
- Checklist
- How Has This Been Tested?
- Test Configuration

**Comment by HenrySarukh** [comment]
Hi @GhagSagar23!

Truly, I have not tested it, so I cannot provide you with more information, but I know that many people really need these changes, that would be very nice if you do smth with it, thanks in advance!

**Comment by GhagSagar23** [comment]
No problem @HenrySarukh, I'll do the testing part and release a new version by today's EOD(Indian Standard Time).

**Comment by HenrySarukh** [comment]
> No problem @HenrySarukh, I'll do the testing part and release a new version.

Thanks, that would be very nice!

**Comment by GhagSagar23** [comment]
Hi @HenrySarukh, I am not able to checkout in your branch. I'll do the same changes and publish it.

**Comment by HenrySarukh** [comment]
Hey @GhagSagar23!
Okay, no problem!
For your knowledge, the camerawesome package is using carousel_slider ^4.2.1 version, which is incompatible with newer Flutter versions, it is why that change is crucial for many people.

**Comment by GhagSagar23** [comment]
Hi @HenrySarukh, the code was merged and deployed in [this PR](https://github.com/GhagSagar23/livelyness_detection/pull/18). Also, it is published on [pub.dev](https://pub.dev/packages/livelyness_detection/versions/0.0.1+5) with version `0.0.1+5`.

**Comment by HenrySarukh** [comment]
@GhagSagar23 Thank you very much!

**Pull request closed without merging**
